# Generated by Django 4.2.6 on 2023-10-21 02:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("first_name", models.CharField(blank=True, max_length=32)),
                ("last_name", models.CharField(blank=True, max_length=32)),
                ("title", models.CharField(blank=True, max_length=8)),
                ("license_number", models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["uuid"], name="user_uuid_idx"),
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="uuid",
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["uuid"], name="profile_uuid_idx"),
        ),
    ]
