# Generated by Django 4.2.5 on 2023-10-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["reference_number"], name="client_reference_number_idx"
            ),
        ),
    ]
