# Generated by Django 4.2.5 on 2023-10-04 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "region_code",
                    models.ForeignKey(
                        default="0800000000",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.region",
                        to_field="code",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "city_code",
                    models.ForeignKey(
                        default="0831600000",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.city",
                        to_field="code",
                    ),
                ),
                (
                    "province_code",
                    models.ForeignKey(
                        default="0831600000",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.province",
                        to_field="code",
                    ),
                ),
                (
                    "region_code",
                    models.ForeignKey(
                        default="0800000000",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.region",
                        to_field="code",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="city",
            name="province_code",
            field=models.ForeignKey(
                default="0831600000",
                on_delete=django.db.models.deletion.CASCADE,
                to="regions.province",
                to_field="code",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="region_code",
            field=models.ForeignKey(
                default="0800000000",
                on_delete=django.db.models.deletion.CASCADE,
                to="regions.region",
                to_field="code",
            ),
        ),
    ]
