# Generated by Django 4.2.5 on 2023-10-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="city",
            index=models.Index(fields=["code"], name="city_code_idx"),
        ),
        migrations.AddIndex(
            model_name="district",
            index=models.Index(fields=["code"], name="district_code_idx"),
        ),
        migrations.AddIndex(
            model_name="province",
            index=models.Index(fields=["code"], name="province_code_idx"),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(fields=["code"], name="region_code_idx"),
        ),
    ]
