# Generated by Django 4.2.5 on 2023-10-06 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0002_city_city_code_idx_district_district_code_idx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="city",
            old_name="province_code",
            new_name="province",
        ),
        migrations.RenameField(
            model_name="district",
            old_name="city_code",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="district",
            old_name="province_code",
            new_name="province",
        ),
        migrations.RenameField(
            model_name="district",
            old_name="region_code",
            new_name="region",
        ),
        migrations.RenameField(
            model_name="province",
            old_name="region_code",
            new_name="region",
        ),
    ]
