# Generated by Django 4.2.5 on 2023-10-06 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0003_rename_province_code_city_province_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="city",
            old_name="region_code",
            new_name="region",
        ),
    ]
