# Generated by Django 4.2.5 on 2023-10-06 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="client_reference_number",
            new_name="client",
        ),
    ]
