# Generated by Django 4.2.6 on 2023-10-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0002_rename_client_reference_number_record_client"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="record",
            index=models.Index(fields=["uuid"], name="record_uuid_idx"),
        ),
    ]
